# Generated by Django 5.1.8 on 2025-04-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.PositiveIntegerField(default=10, help_text='Total number of questions'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='objective_ratio',
            field=models.PositiveSmallIntegerField(help_text='Percentage of objective questions'),
        ),
    ]
