# Generated by Django 5.1.8 on 2025-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_total_questions_alter_exam_objective_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('preparing', '준비중'), ('ongoing', '진행중'), ('finished', '종료')], default='preparing', max_length=10),
        ),
    ]
