# Generated by Django 5.1.8 on 2025-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
