volumes:
  csplanet_local_postgres_data: {}
  csplanet_local_postgres_data_backups: {}
  csplanet_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: csplanet_local_django
    container_name: csplanet_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.env
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: csplanet_production_postgres
    container_name: csplanet_local_postgres
    volumes:
      - csplanet_local_postgres_data:/var/lib/postgresql/data
      - csplanet_local_postgres_data_backups:/backups
    environment:
      - POSTGRES_USER=csplanet
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=csplanet_local
      - POSTGRES_PORT=5432

  redis:
    image: docker.io/redis:6
    container_name: csplanet_local_redis

    volumes:
      - csplanet_local_redis_data:/data

  celeryworker:
    <<: *django
    image: csplanet_local_celeryworker
    container_name: csplanet_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: csplanet_local_celerybeat
    container_name: csplanet_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: csplanet_local_flower
    container_name: csplanet_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
